language: node_js
dist: xenial
cache:
  directories:
    - "node_modules"
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  global:
    # ENVKEY 8kX3…
    - secure: "euCYmXn2iCIhJC/E92UltN2FDlB3vv9qEas2T4A8rdWtIjToOsax424B28LpgraSwIP5ix82hsBM73bmiVxo/JtSy8MeEzB2kOUYHdyvon91MIxflYVYHIIJDuDn4nCB4jz6zWTJfJOr5OxUek9pZQjAFoSgp1vjsZNu/PxrxkQDPVPjcOlE6dcZrIOJUTWwFhbg5udv8pR4x4T9snvJBB2DZTa1tIV5rTmoKRVG7Z0VxfFWmxOe59/SoeoEfS5GvDnTMRFmGrDSqL4hJvfue1u0cEF1K8an+8Fnm1RDs2I8EtG0eFDDQ3zGANRROaw6aTBvYQ+cwhMJvxMgPuFoZoPuJlJtktTgdBJib+o85iBUs3eTeMxd5NxRF0seFUjCkMC1tnvkhRzbxQtmki/JB10e6fq5E12jwhPzweq0PuXrZ6LWMS8insf4QYJ4jQoDqqUbPncJpRr1LZ4Vd9d6RIXAsQlvJXbhU73MgM9FgQQJTq7Z1Hp3t14UMav0uBXcdGCMmUoDeXMwHuN8GlRDhslFjEHkVKLkwLHedlvr9zlr2fzR/jkp1WjN++BBPcMjO1BUmg5nFe/gNp5AZy2P/lMe92869L4Qfbo2C4Shwr4tBMhCtDJfWv41sjbiof1Z4xtQXB7cIaBxcyy9yyOf/xBRsfy7QskRb6tSl56nRcM="
before_install:
  - curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash
  - eval $(envkey-source)
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
install:
  - npm install
before_script:
  - npm run build
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run publish
    on:
      branch: master
notifications:
  email: false
