# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Fetch and set NPM token
      env:
        ENVKEY: ${{ secrets.ENVKEY }}
      run: >-
        curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh
        | bash
        && eval $(envkey-source)
        && echo "NPM_TOKEN=${NPM_TOKEN}" >> $GITHUB_ENV
        && echo "::add-mask::$NPM_TOKEN"

    - name: Set NPM Token
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run build
    - run: docker pull postgres:9.4
    - run: npm test

    - name: Deploy Production
      if: github.ref == 'refs/heads/master'
      run: npm run publish
